/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.KhachHangDAO;
import dao.SanBongDAO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.BookingTime;
import model.KhachHang;
import model.PhieuDatSan;
import model.SanBong;

/**
 *
 * @author ADMIN
 */
public class TimKHJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TimKHJFrame
     */
    private ArrayList<KhachHang> list;
    SanBong san = new SanBong();
    BookingTime time = new BookingTime();

    public TimKHJFrame(SanBong sanBong, BookingTime bookingTime) {
        san.setMaSan(sanBong.getMaSan());
        san.setLoaiSan(sanBong.getLoaiSan());
        san.setKhungGio(sanBong.getKhungGio());
        san.setGia(sanBong.getGia());
        time.setNgayBatdau(bookingTime.getNgayBatdau());
        time.setNgayKetthuc(bookingTime.getNgayKetthuc());
        initComponents();
        list = new ArrayList<KhachHang>();
        jtlTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2 && jtlTable.getSelectedRow() != -1) {
                    try {
                        DefaultTableModel model = (DefaultTableModel) jtlTable.getModel();
                        int selectRowIndex = jtlTable.getSelectedRow();
                        selectRowIndex = jtlTable.convertRowIndexToModel(selectRowIndex);
                        KhachHang khachHang = new KhachHang();
                        khachHang.setMaKH(jtlTable.getValueAt(selectRowIndex, 0).toString());
                        khachHang.setTenKH(jtlTable.getValueAt(selectRowIndex, 1).toString());
                        khachHang.setSdt(jtlTable.getValueAt(selectRowIndex, 2).toString());
                        khachHang.setDiaChi(jtlTable.getValueAt(selectRowIndex, 3).toString());
//                    System.out.println(sanBong.getMaSan() + " " + sanBong.getLoaiSan() + " " + sanBong.getKhungGio() + " " + sanBong.getGia());
//                    System.out.println(bookingTime.getNgayBatdau() + "++" + bookingTime.getNgayKetthuc());

                        JFrame jframe = new DatSanJFrame(khachHang, sanBong, bookingTime);
                        jframe.setVisible(true);
                        jframe.setTitle("Chi tiết phiếu đặt sân");
                        dispose();
                    } catch (SQLException ex) {
                        Logger.getLogger(TimKHJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtlTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfTenKH = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtlTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtlTable);

        jLabel1.setText("Tên Khách Hàng");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm Khách Hàng Mới");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(288, 288, 288))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        KhachHangDAO khDao = new KhachHangDAO();
        try {
            list = khDao.searchKhachHang(jtfTenKH.getText().trim());
        } catch (SQLException ex) {

        }
        String[] column = {"Mã Khách Hàng", "Tên Khách Hàng", "Số điện thoại", "Địa Chỉ"};
        String[][] value = new String[list.size()][5];
        for (int i = 0; i < list.size(); i++) {
            value[i][0] = list.get(i).getMaKH() + "";
            value[i][1] = list.get(i).getTenKH() + "";
            value[i][2] = list.get(i).getSdt() + "";
            value[i][3] = list.get(i).getDiaChi() + "";
        }
        DefaultTableModel model = new DefaultTableModel(value, column) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jtlTable.setModel(model);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        JFrame jframe = new ThemKHJFrame(san, time);
        jframe.setVisible(true);
        jframe.setTitle("Chi tiết phiếu đặt sân");
        dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TimKHJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TimKHJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TimKHJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TimKHJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TimKHJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfTenKH;
    private javax.swing.JTable jtlTable;
    // End of variables declaration//GEN-END:variables
}
